services:

  hbase-master:
    image: blueskyareahm/hbase-base:2.1.3
    container_name: hbase-master
    command: master
    ports:
      - 16000:16000
      - 16010:16010

  hbase-regionserver:
    image: blueskyareahm/hbase-base:2.1.3
    container_name: hbase-regionserver
    command: regionserver
    ports:
      - 16030:16030
      - 16201:16201
      - 16301:16301

  zookeeper:
    image: blueskyareahm/hbase-zookeeper:3.4.13
    container_name: zookeeper
    ports:
      - 2181:2181